// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ApiExplorerController from "./api_explorer_controller"
import ThemeController from "./theme_controller"
application.register("api-explorer", ApiExplorerController)
application.register("theme", ThemeController)
